
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EJC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vwChart
{

    public short ID { get; set; }

    public string Name { get; set; }

    public short Group { get; set; }

    public Nullable<byte> Period { get; set; }

    public string PeriodName { get; set; }

}

}
