
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EJC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vwData
{

    public int ID { get; set; }

    public short Chart { get; set; }

    public string ChartName { get; set; }

    public short Line { get; set; }

    public string LineName { get; set; }

    public Nullable<byte> LineType { get; set; }

    public string LineTypeName { get; set; }

    public Nullable<byte> Period { get; set; }

    public string PeriodName { get; set; }

    public System.DateTime Date { get; set; }

    public decimal Value { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<int> Month { get; set; }

}

}
