
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EJC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vwLine
{

    public short ID { get; set; }

    public string Name { get; set; }

    public short Chart { get; set; }

    public Nullable<byte> LineType { get; set; }

    public string LineTypeName { get; set; }

}

}
